# image: https://hub.docker.com/r/dgraph/dgraph/
# docs: https://dgraph.io/docs/get-started/#step-1-run-dgraph

version: '3.8'

services:

  dgraph:
    image: dgraph/standalone:${DB_DGRAPH_VERSION}
    container_name: ${APP_NAME}
    restart: always
    ports:
     - 8080:8080
     - 8000:8000
     - 9080:9080
    command: ["/run.sh", "--bindall"]
    volumes:
     - dgraph:/dgraph

networks:
  default:
      name: ${APP_NAME}

volumes:
  dgraph:
